In [1]:
import pandas as pd

In [2]:
df = pd.read_excel("SkillCraft_Task2_Cleaned.xlsx")
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Country/Region,City,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,1,US-2023-103800,2023-01-03,2023-01-07,Standard Class,DP-13000,Darren Powers,Consumer,United States,Houston,...,77095,Central,OFF-PA-10000174,Office Supplies,Paper,"Message Book, Wirebound, Four 5 1/2"" X 4"" Form...",16.448,2,0.2,5.5512
1,2,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-BI-10004094,Office Supplies,Binders,GBC Standard Plastic Binding Systems Combs,3.540,2,0.8,-5.4870
2,3,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-LA-10003223,Office Supplies,Labels,Avery 508,11.784,3,0.2,4.2717
3,4,US-2023-112326,2023-01-04,2023-01-08,Standard Class,PO-19195,Phillina Ober,Home Office,United States,Naperville,...,60540,Central,OFF-ST-10002743,Office Supplies,Storage,SAFCO Boltless Steel Shelving,272.736,3,0.2,-64.7748
4,5,US-2023-141817,2023-01-05,2023-01-12,Standard Class,MB-18085,Mick Brown,Consumer,United States,Philadelphia,...,19143,East,OFF-AR-10003478,Office Supplies,Art,Avery Hi-Liter EverBold Pen Style Fluorescent ...,19.536,3,0.2,4.8840

In [3]:
df[['Sales', 'Quantity', 'Discount', 'Profit']].describe()

              Sales      Quantity      Discount        Profit
count  10194.000000  10194.000000  10194.000000  10194.000000
mean     228.225854      3.791838      0.155385     28.673417
std      619.906839      2.228317      0.206249    232.465115
min        0.444000      1.000000      0.000000  -6599.978000
25%       17.220000      2.000000      0.000000      1.760800
50%       53.910000      3.000000      0.200000      8.690000
75%      209.500000      5.000000      0.200000     29.297925
max    22638.480000     14.000000      0.800000   8399.976000

In [4]:
df.groupby('Category')[['Sales', 'Profit']].sum().sort_values('Profit', ascending=False)

                       Sales       Profit
Category
Technology       839893.2790  146543.3756
Office Supplies  731893.3140  126023.4434
Furniture        754747.7613   19729.9956

In [5]:
df.groupby('Region')[['Sales', 'Profit']].sum().sort_values('Profit', ascending=False)

               Sales       Profit
Region
West     739813.6085  110798.8170
East     691828.1680   94883.2603
South    391721.9050   46749.4303
Central  503170.6728   39865.3070

In [6]:
df.groupby('Sub-Category')[['Sales', 'Profit']].sum().sort_values('Profit', ascending=False)

                    Sales      Profit
Sub-Category
Copiers       150745.2900  56093.9365
Phones        331842.6400  45050.8265
Accessories   167380.3180  41936.6357
Paper          79540.5380  34511.5070
Binders       207354.8810  31426.1003
Chairs        335768.2490  27223.5323
Storage       224644.5540  21285.1115
Appliances    108213.1850  18329.4844
Furnishings    95598.1260  13891.7430
Envelopes      16528.3620   6988.0247
Art            27659.0140   6653.1962
Labels         12695.0420   5572.7780
Machines      189925.0310   3461.9769
Fasteners       8532.2400   2428.6358
Supplies       46725.4980  -1171.3945
Bookcases     115361.2043  -3632.0736
Tables        208020.1820 -17753.2061

In [7]:
df[['Discount', 'Profit']].corr()

          Discount    Profit
Discount  1.000000 -0.218882
Profit   -0.218882  1.000000

In [8]:
df[['Sales', 'Profit']].sum()

Sales     2.326534e+06
Profit    2.922968e+05
dtype: float64

In [9]:
print("BUSINESS INSIGHTS")
print("------------------")
print("1. Technology has the highest sales and profit.")
print("2. West is the best-performing region.")
print("3. Copiers are the most profitable sub-category, while Tables have the highest loss.")
print("4. Higher discounts show a weak negative relationship with profit.")
print("5. Total Sales =", round(df['Sales'].sum(), 2))
print("6. Total Profit =", round(df['Profit'].sum(), 2))

BUSINESS INSIGHTS
------------------
1. Technology has the highest sales and profit.
2. West is the best-performing region.
3. Copiers are the most profitable sub-category, while Tables have the highest loss.
4. Higher discounts show a weak negative relationship with profit.
5. Total Sales = 2326534.35
6. Total Profit = 292296.81